name: glade
adopt-info: glade
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  glade:
    interface: dbus
    bus: session
    name: org.gnome.Glade
apps:
  glade:
    command: usr/bin/glade
    extensions: [gnome-3-38]
    environment:
      GLADE_CATALOG_SEARCH_PATH: "$SNAP/usr/share/glade/catalogs"
      GLADE_MODULE_SEARCH_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glade/modules"
      GLADE_PIXMAP_DIR: "$SNAP/usr/share/glade/pixmaps"
    plugs:
      - home
      - network
      - removable-media
      - mount-observe
    common-id: org.gnome.Glade

parts:
  glade:
    source: https://gitlab.gnome.org/GNOME/glade.git
    source-branch: glade-3-38
    source-type: git
    parse-info: [usr/share/metainfo/org.gnome.Glade.appdata.xml]
    plugin: meson
    meson-version: "0.55.0"
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags | sed 's/GLADE_//g'|sed 's/_/./g')
    override-build: |
      sed -i.bak -e 's|=org.gnome.Glade$|=snap.$SNAPCRAFT_PROJECT_NAME.org.gnome.Glade|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Glade.desktop.in.in
      sed -i.bak '\|<id>org.gnome.Glade</id>|a<icon type="stock">snap.$SNAPCRAFT_PROJECT_NAME.org.gnome.Glade</icon>' $SNAPCRAFT_PART_SRC/data/org.gnome.Glade.appdata.xml.in
      sed -i.bak -e 's|symlink_media: true,|symlink_media: false,|g' $SNAPCRAFT_PART_SRC/help/meson.build
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Glade.svg $SNAPCRAFT_PART_INSTALL/meta/gui/icon.svg
      cp -r $SNAPCRAFT_PART_INSTALL/usr/share/icons $SNAPCRAFT_PART_INSTALL/meta/gui/
      for i in `find $SNAPCRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`
      do
        mv $i "`dirname $i`/snap.$SNAPCRAFT_PROJECT_NAME.`basename $i`"
      done

    build-packages:
      - gnome-common
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - python-gi-dev
      - python3-dev
      - gtk-doc-tools
      - yelp-tools
      - intltool
      - gobject-introspection
      - libgirepository1.0-dev
    stage-packages:
      - libpython3.9
